--------------------------------------------------------
--  Order to import db efel   
--------------------------------------------------------
@/Users/manuel/workspace/stampati/eFelDatabase/APPO_FIRMATARIO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/APPO_XML.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ATTIVITACOMPOSTAMPASEQUENZ.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOMOTIVOTRASF.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPORICHIEDENTITRASF.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOTRASFERIMENTOSEDE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPODESTINATRICHRIMESS.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ASSEGNAZIONETRASFERIMENTO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ATTIVITACOMPOSTPSEQALT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_COMMISSIONE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_COMMISSIONEASSEGNATA.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_COMMISSIONERELATORE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_CORREZIONEPDLMESS.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSTRALCIO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPONAVETTE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ATTOSENATOPDLMESSASENATO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_DOC.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ERRORI.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FASE_STATO_SCARTO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FILE_ORIGINE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPODELIBERAZIONEATTO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPORICEVIMENTOPDL.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOMOTIVORIPRESAUTOMAT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_LEGISLATURA.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOCONCLUSIONE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOGRUPPONATURAPDL.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSEQUENZA.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPONATURAPDL.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOTIPOLOGIAPDL.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOTIPOLOGIAPDL_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ESTREMIATTOPDL.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFIRMATARIO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIOATTOPDL.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIODEPUTATO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIOGOVERNO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIOPDLATTOSENATO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIOSENATORE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_LEGGEPUBBLICAZIONE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_REGIONE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIOREGIONE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_LOG_DATI.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_LOG_PDL.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_MEMBROGOVERNO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_MESSAGGIO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_MESSAGGIPROCESSO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOATTIVAZIONEPARERE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPORIFERIMENTONORM.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOMODIFICAASSEGNAZIONE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLASSEGNAZIONECONSULT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PARERECOMM.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOPARLAMENTARE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PARLAMENTARE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLABBINAMENTO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLABBINAMENTOPDLABBINATI.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLASSEGNAZIONE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLASSEGNAZIONECC.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLATTIVITACOMPOSTAMPA.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLATTOSENATO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLDOCUMENTOCONNESSO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSEMBLEARELATORE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSRELAZIOCOM.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSRELAZIOMIN.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLMESS.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOORGANOESAME.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAME.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOESITOESAMEASS.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSEMBLEA.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOINFORMAZIONERELAZIONE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSEMBLEARELAZIO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOESITOESAMELEGISL.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMELEGISLATIVA.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSTATO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASESTATO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLMESSASENATO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLMESSRINVIOPDR.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLRINVIOPDR.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_STRALCIOCOMMISSIONEPROP.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOASSEGNAZIONE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOASSEGNAZIONESEDE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOATTIVITACOMPOSTAMPA.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOCRITICITA.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPODESTINATARIOMESS.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOESITOCONFLCOMP.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOESITODELIBERA.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOESITOPARERECOMM.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOEVENTOCOMPONENTE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASESTATOCOMPPROC.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOLIVELLOGRUPPOVOCI.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOLOGIADOC.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOLOGIANAVETTE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOLOGIASTRALCIO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOMESSAGGIO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOMOTIVORIMESSIONE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPONATURACONFLCOMP.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPONATURADOCUMENTO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPONATURADOCUMENTOART.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOOGGRICHCONFLCOMP.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOORGANODELIBERSTR.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOPARERERICHIESTO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPORAMOPARLAMENTO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOREGIONEPROVINCIA.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSEDE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSTATO_BIS.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSTATO_SL.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOTITOLOATTOPDL.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TITOLOATTOPDL.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_STRALCIOATTOPDL.sql
@/Users/manuel/workspace/stampati/eFelDatabase/MICROSOFTDTPROPERTIES.sql
@/Users/manuel/workspace/stampati/eFelDatabase/OBJ_G_MIGRATION.sql
@/Users/manuel/workspace/stampati/eFelDatabase/PLAN_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SCARTI_ABBINATI.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_SERVIZIO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_SISTEMA.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_TIPO_ACCESSO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_TIPO_UTENTE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_UTENTE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_UTENTE_PASSWOD_MODIFICATA.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_PROCESSO_SISTEMA.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_ABILITAZIONE_UTENTE_PROCES.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_COMPONENTEPROCESSO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_PROCESSO_SERVIZIO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_PROCESSO_SERVIZIO_TIPO_UTE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLFASESTATO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/STAMPATIPDL_RELATORI.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SQLN_EXPLAIN_PLAN.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SKLAV_PDLESAMESENATO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/T_SISTEMAVERSIONE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/T_TIPOSISTEMAOPERATIVO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/T1141R_OPAR.sql
@/Users/manuel/workspace/stampati/eFelDatabase/TIPOSTATO_SCHEDELAVORI.sql
@/Users/manuel/workspace/stampati/eFelDatabase/VTNRIEPILOGOPDL.sql
@/Users/manuel/workspace/stampati/eFelDatabase/T_SISTEMAVERSIONEINST.sql

-- DATA

@/Users/manuel/workspace/stampati/eFelDatabase/APPO_FIRMATARIO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/APPO_XML_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ATTIVITACOMPOSTAMPASEQUENZ_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ATTIVITACOMPOSTPSEQALT_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ATTOSENATOPDLMESSASENATO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOTRASFERIMENTOSEDE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPORICHIEDENTITRASF_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOMOTIVOTRASF_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPODESTINATRICHRIMESS_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ASSEGNAZIONETRASFERIMENTO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ASSEGNAZIONETRASFERIMENTO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_COMMISSIONE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_COMMISSIONEASSEGNATA_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_COMMISSIONERELATORE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_CORREZIONEPDLMESS_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_DOC_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ERRORI_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPORICEVIMENTOPDL_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOMOTIVORIPRESAUTOMAT_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_LEGISLATURA_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSEQUENZA_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOGRUPPONATURAPDL_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPONATURAPDL_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOCONCLUSIONE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPODELIBERAZIONEATTO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ESTREMIATTOPDL_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FASE_STATO_SCARTO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FILE_ORIGINE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFIRMATARIO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIOATTOPDL_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIODEPUTATO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIOGOVERNO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIOPDLATTOSENATO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_REGIONE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIOREGIONE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIOSENATORE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_LEGGEPUBBLICAZIONE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_LOG_DATI_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_LOG_PDL_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_MEMBROGOVERNO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_MESSAGGIO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_MESSAGGIPROCESSO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLASSEGNAZIONECONSULT_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOATTIVAZIONEPARERE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPORIFERIMENTONORM_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PARERECOMM_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PARLAMENTARE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLABBINAMENTO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLABBINAMENTOPDLABBINATI_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLASSEGNAZIONE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLASSEGNAZIONECC_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLATTIVITACOMPOSTAMPA_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLATTOSENATO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLDOCUMENTOCONNESSO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOORGANOESAME_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAME_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOESITOESAMEASS_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSEMBLEA_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSEMBLEARELATORE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSEMBLEARELAZIO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSRELAZIOCOM_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSRELAZIOMIN_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOESITOESAMELEGISL_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMELEGISLATIVA_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLFASESTATO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLMESS_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLMESSASENATO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLMESSRINVIOPDR_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLRINVIOPDR_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOORGANODELIBERSTR_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_STRALCIOATTOPDL_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_STRALCIOCOMMISSIONEPROP_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOASSEGNAZIONE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOASSEGNAZIONESEDE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOATTIVITACOMPOSTAMPA_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOCRITICITA_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPODESTINATARIOMESS_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOESITOCONFLCOMP_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOESITODELIBERA_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOESITOPARERECOMM_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOEVENTOCOMPONENTE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSTATO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSTATO_BIS_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSTATO_SL_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASESTATO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASESTATOCOMPPROC_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOINFORMAZIONERELAZIONE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOLIVELLOGRUPPOVOCI_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOLOGIADOC_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOLOGIANAVETTE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOLOGIASTRALCIO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOMESSAGGIO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOMODIFICAASSEGNAZIONE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOMOTIVORIMESSIONE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPONATURACONFLCOMP_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPONATURADOCUMENTO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPONATURADOCUMENTOART_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPONAVETTE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOOGGRICHCONFLCOMP_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOPARERERICHIESTO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOPARLAMENTARE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPORAMOPARLAMENTO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOREGIONEPROVINCIA_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSEDE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSTRALCIO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOTITOLOATTOPDL_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TITOLOATTOPDL_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/MICROSOFTDTPROPERTIES_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/OBJ_G_MIGRATION_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/PLAN_TABLE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SCARTI_ABBINATI_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_TIPO_UTENTE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_SISTEMA_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_PROCESSO_SISTEMA_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_TIPO_ACCESSO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_SERVIZIO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_UTENTE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_ABILITAZIONE_UTENTE_PROCES_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_COMPONENTEPROCESSO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_PROCESSO_SERVIZIO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_PROCESSO_SERVIZIO_TIPO_UTE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_UTENTE_PASSWOD_MODIFICATA_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SKLAV_PDLESAMESENATO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SQLN_EXPLAIN_PLAN_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/STAMPATIPDL_RELATORI_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/T_SISTEMAVERSIONE_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/T_TIPOSISTEMAOPERATIVO_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/T_SISTEMAVERSIONEINST_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/T1141R_OPAR_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/TIPOSTATO_SCHEDELAVORI_DATA_TABLE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/VTNRIEPILOGOPDL_DATA_TABLE.sql

------- INDEXES

@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079328.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ASSEGNAZIONETRASFERIMENTOI.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ASSEGNAZIONETRASFERIMENTO6.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ASSEGNAZIONETRASFERIMENTO4.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ASSEGNAZIONETRASFERIMENTO3.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ASSEGNAZIONETRASFERIMENTO2.sql
@/Users/manuel/workspace/stampati/eFelDatabase/ASSEGNAZIONETRASF_LEGW_IDEAP.sql
@/Users/manuel/workspace/stampati/eFelDatabase/PK_ATTIVITACOMPOSTAMPASEQUENZ.sql
@/Users/manuel/workspace/stampati/eFelDatabase/PKATTIVITACOMPOSTAMPA.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ATTIVITACOMPOSTPSEQALTNDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079325.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079324.sql
@/Users/manuel/workspace/stampati/eFelDatabase/COMMISSIONEASS_LEGW_IDEAP.sql
@/Users/manuel/workspace/stampati/eFelDatabase/COMMISSIONEASSEGNATA_PK.sql
@/Users/manuel/workspace/stampati/eFelDatabase/COMMISSIONERELATORE_PK.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079321.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_DOC_PK.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ESTREMIATTOPDLIF4_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ESTREMIATTOPDLIF3_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ESTREMIATTOPDLIF2_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ESTREMIATTOPDLIF1_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ESTREMIATTOPDLIF6_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/IDX_DATIRIASSUNTIVI.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079319.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FILE_ORIGINE_PK.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIOATTOPDLIF2_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FIRMATARIOATTOPDL_LEGW_IDEAP.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079317.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079316.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FIRMATARIODEPPDL_LEGW_IDEAP.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079315.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FIRMATARIOGOVPDL_LEGW_IDEAP.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIOREGIONEIF2_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079314.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079313.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079312.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079311.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_LOG_PDL_PK.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079309.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_MESSAGGIOPK_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_MESSAGGIPROCESSOIF4_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_MESSAGGIPROCESSOIF3_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079308.sql
@/Users/manuel/workspace/stampati/eFelDatabase/PK_PARERECOMM.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079306.sql
@/Users/manuel/workspace/stampati/eFelDatabase/ABBINAMENTO_LEGW_IDEAP.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079305.sql
@/Users/manuel/workspace/stampati/eFelDatabase/ABBINAMENTOPDLABB_LEGW_IDEAP.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079304.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLASSEGNAZIONEIF4_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLASSEGNAZIONEIF3_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLASSEGNAZIONEIF2_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/ASSEGNAZIONE_LEGW_IDEAP.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079303.sql
@/Users/manuel/workspace/stampati/eFelDatabase/PK_ASSEGNAZIONECC.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLASSEGNAZIONECCIF4_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLASSEGNAZIONECCIF3_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLASSEGNAZIONECCIF2_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/PK_ASSCONSULT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/PKPDLATTIVITACOMPOSTAMPA.sql
@/Users/manuel/workspace/stampati/eFelDatabase/ATTIVITACOMPOSTAMPA_LEGW_IDEAP.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079299.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLATTOSENATOIF3_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLATTOSENATOIF2_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079298.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079297.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSEMBLEAIF2_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/PK_ESAMEASSRELATORE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/PK_ESAMEASSRELAZIO.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSRELAZIOMIN_PK.sql
@/Users/manuel/workspace/stampati/eFelDatabase/PK_ESAMELEGISL.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMELEGISLATIVAIF2_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0012133.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079291.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079290.sql
@/Users/manuel/workspace/stampati/eFelDatabase/NDX_FEL_PDLRINVIOPDR.sql
@/Users/manuel/workspace/stampati/eFelDatabase/PK_FEL_PDLRINVIOPDL.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079289.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_STRALCIOATTOPDLIF2_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_STRALCIOATTOPDLIF1_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_STRALCIOATTOPDLPK_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/PK_STRALCOMPROP.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079287.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOASSEGNAZIONESEDEIF1_ND.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079286.sql
@/Users/manuel/workspace/stampati/eFelDatabase/PK_TIPOATTIVITACOMPOSTAMPA.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079284.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079283.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079282.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079281.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079280.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079279.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079278.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079277.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079276.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079275.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079274.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079273.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASEIF1_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASESTATOIF3_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASESTATOIF2_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASESTATOIF1_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079272.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASESTATOCOMPPROC6_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASESTATOCOMPPROC5_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASESTATOCOMPPROC4_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASESTATOCOMPPROC3_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASESTATOCOMPPROC2_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASESTATOCOMPPROC1_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079271.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079270.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079269.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079268.sql
@/Users/manuel/workspace/stampati/eFelDatabase/PK_TIPOLIVELLOGRUPPOVOCI.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079266.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079265.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079264.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079263.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079262.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079261.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079260.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079259.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079258.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPONATURAPDLIF1_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079257.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079256.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079255.sql
@/Users/manuel/workspace/stampati/eFelDatabase/PK_TIPOORGANODELIBERSTR.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079253.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079252.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079251.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079250.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079249.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079248.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079247.sql
@/Users/manuel/workspace/stampati/eFelDatabase/PK_TIPORIFERIMENTONORM.sql
@/Users/manuel/workspace/stampati/eFelDatabase/PK_CODICETIPOSEQUENZA.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSTATOIF1_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079244.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSTATOIF1_BIS_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079243.sql
@/Users/manuel/workspace/stampati/eFelDatabase/PK_TIPOSTATO_SL.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079241.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079240.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079239.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079238.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TITOLOATTOPDL_NDX1.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079237.sql
@/Users/manuel/workspace/stampati/eFelDatabase/TITOLOATTOPDL_LEGW_IDEAP.sql
@/Users/manuel/workspace/stampati/eFelDatabase/MICROSOFT_PK_DTPROPERTIES.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_ABILITAZIONE_UTENTE_PR_FK3.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_ABILITAZIONE_UTENTE_PR_FK2.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_ABILITAZIONE_UTENTE_PR_FK1.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079232.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_COMPPROC3_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_COMPPROC2_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_COMPPROC1_NDX.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079231.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_PROCESSO_SERVIZIO_FK3.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_PROCESSO_SERVIZIO_FK2.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_PROCESSO_SERVIZIO_FK1.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079230.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_PROCESSO_SERVIZIO_TIPO_FK3.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_PROCESSO_SERVIZIO_TIPO_FK2.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_PROCESSO_SERVIZIO_TIPO_FK1.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079229.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_PROCESSO_SISTEMA_FK1.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079228.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079227.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079226.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079225.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079224.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_UTENTE_FK3.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_UTENTE_FK2.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_UTENTE_FK1.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079223.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_UTENTE_PASSWOD_MODIFIC_FK1.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079222.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SKLAV_PDLESAMESENATO_PK.sql
@/Users/manuel/workspace/stampati/eFelDatabase/XIF1T_SISTEMAVERSIONE.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079220.sql
@/Users/manuel/workspace/stampati/eFelDatabase/XIF2T_SISTEMAVERSIONEINST.sql
@/Users/manuel/workspace/stampati/eFelDatabase/XIF1T_SISTEMAVERSIONEINST.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079219.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SYS_C0079218.sql

-- CONSTRAINTS


@/Users/manuel/workspace/stampati/eFelDatabase/APPO_FIRMATARIO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ATTIVITACOMPOSTAMPASEQUENZ_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ATTIVITACOMPOSTPSEQALT_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ATTOSENATOPDLMESSASENATO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_COMMISSIONE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_COMMISSIONEASSEGNATA_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_COMMISSIONERELATORE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_CORREZIONEPDLMESS_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_DOC_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ESTREMIATTOPDL_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FILE_ORIGINE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIOATTOPDL_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIODEPUTATO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIOGOVERNO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIOPDLATTOSENATO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIOREGIONE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIOSENATORE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_LEGGEPUBBLICAZIONE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_LEGISLATURA_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_LOG_PDL_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_MEMBROGOVERNO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_MESSAGGIO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_MESSAGGIPROCESSO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PARERECOMM_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PARLAMENTARE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLABBINAMENTO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLABBINAMENTOPDLABBINATI_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLASSEGNAZIONE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLASSEGNAZIONECC_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLASSEGNAZIONECONSULT_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLATTIVITACOMPOSTAMPA_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLATTOSENATO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLDOCUMENTOCONNESSO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAME_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSEMBLEA_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSEMBLEARELATORE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSEMBLEARELAZIO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSRELAZIOCOM_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSRELAZIOMIN_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMELEGISLATIVA_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLFASESTATO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLMESS_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLMESSASENATO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLMESSRINVIOPDR_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLRINVIOPDR_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_REGIONE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_STRALCIOATTOPDL_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_STRALCIOCOMMISSIONEPROP_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOASSEGNAZIONE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOASSEGNAZIONESEDE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOATTIVAZIONEPARERE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOATTIVITACOMPOSTAMPA_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOCONCLUSIONE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOCRITICITA_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPODELIBERAZIONEATTO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPODESTINATARIOMESS_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPODESTINATRICHRIMESS_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOESITOCONFLCOMP_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOESITODELIBERA_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOESITOESAMEASS_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOESITOESAMELEGISL_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOESITOPARERECOMM_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOEVENTOCOMPONENTE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASESTATO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASESTATOCOMPPROC_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFIRMATARIO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOGRUPPONATURAPDL_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOINFORMAZIONERELAZIONE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOLIVELLOGRUPPOVOCI_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOLOGIADOC_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOLOGIANAVETTE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOLOGIASTRALCIO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOMESSAGGIO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOMODIFICAASSEGNAZIONE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOMOTIVORIMESSIONE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOMOTIVORIPRESAUTOMAT_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOMOTIVOTRASF_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPONATURACONFLCOMP_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPONATURADOCUMENTO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPONATURADOCUMENTOART_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPONATURAPDL_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPONAVETTE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOOGGRICHCONFLCOMP_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOORGANODELIBERSTR_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOORGANOESAME_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOPARERERICHIESTO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOPARLAMENTARE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPORAMOPARLAMENTO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOREGIONEPROVINCIA_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPORICEVIMENTOPDL_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPORICHIEDENTITRASF_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPORIFERIMENTONORM_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSEDE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSEQUENZA_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSTATO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSTATO_BIS_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSTATO_SL_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSTRALCIO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOTIPOLOGIAPDL_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOTITOLOATTOPDL_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOTRASFERIMENTOSEDE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TITOLOATTOPDL_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/MICROSOFTDTPROPERTIES_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_ABILITAZIONE_UTENTE_PROCES_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_COMPONENTEPROCESSO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_PROCESSO_SERVIZIO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_PROCESSO_SERVIZIO_TIPO_UTE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_PROCESSO_SISTEMA_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_SERVIZIO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_SISTEMA_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_TIPO_ACCESSO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_TIPO_UTENTE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_UTENTE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_UTENTE_PASSWOD_MODIFICATA_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SKLAV_PDLESAMESENATO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/T_SISTEMAVERSIONE_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/T_SISTEMAVERSIONEINST_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/T_TIPOSISTEMAOPERATIVO_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/T1141R_OPAR_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/TIPOSTATO_SCHEDELAVORI_CONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ASSEGNAZIONETRASFERIMENTO_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ATTOSENATOPDLMESSASENATO_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_COMMISSIONEASSEGNATA_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_ESTREMIATTOPDL_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIOATTOPDL_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIODEPUTATO_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIOGOVERNO_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIOREGIONE_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_FIRMATARIOSENATORE_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_LEGGEPUBBLICAZIONE_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PARERECOMM_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PARLAMENTARE_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLABBINAMENTO_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLABBINAMENTOPDLABBINATI_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLASSEGNAZIONECC_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLASSEGNAZIONECONSULT_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLATTOSENATO_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAME_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSEMBLEA_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSEMBLEARELATORE_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSEMBLEARELAZIO_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSRELAZIOCOM_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMEASSRELAZIOMIN_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLESAMELEGISLATIVA_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_PDLFASESTATO_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_STRALCIOATTOPDL_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOESITOESAMEASS_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASE_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASESTATO_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOFASESTATOCOMPPROC_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPONATURAPDL_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSTATO_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TIPOSTATO_BIS_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/FEL_TITOLOATTOPDL_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_ABILITAZIONE_UTENTE_PROCES_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_PROCESSO_SERVIZIO_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_PROCESSO_SERVIZIO_TIPO_UTE_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_PROCESSO_SISTEMA_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_UTENTE_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SIC_UTENTE_PASSWOD_MODIFICATA_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/SKLAV_PDLESAMESENATO_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/T_SISTEMAVERSIONE_REFCONSTRAINT.sql
@/Users/manuel/workspace/stampati/eFelDatabase/T_SISTEMAVERSIONEINST_REFCONSTRAINT.sql
